site:
  title: Industrializing Inference Maximizing GPU ROI with llm-d
  start_page: rhoai3-llmd::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
